# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 242)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 363, 27))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineLogin = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineLogin.setGeometry(QtCore.QRect(60, 80, 321, 25))
        self.lineLogin.setText("")
        self.lineLogin.setMaxLength(50)
        self.lineLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineLogin.setObjectName("lineLogin")
        self.linePassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.linePassword.setGeometry(QtCore.QRect(60, 120, 321, 25))
        self.linePassword.setAutoFillBackground(False)
        self.linePassword.setText("")
        self.linePassword.setMaxLength(16)
        self.linePassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.linePassword.setObjectName("linePassword")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 160, 89, 25))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Войти в аккаунт"))
        self.lineLogin.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.linePassword.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.pushButton.setText(_translate("MainWindow", "Вход"))
